#!/bin/bash
echo "🦈 Starting Shark Chat Extension..."
echo ""
echo "Please follow these steps in VS Code:"
echo "1. Press Ctrl+Shift+P to open Command Palette"
echo "2. Type: 🦈 Start Shark Chat Receiver"
echo "3. Press Enter"
echo ""
echo "You should see '🦈 Shark Chat: Connected' in the status bar"
echo ""
echo "Then test by:"
echo "1. Open test-output.txt in VS Code"
echo "2. Place cursor in the file"
echo "3. Go to the website and type a message"
echo "4. Press Enter - text should appear in VS Code!"
